# Generated by Django 5.0.1 on 2024-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userbadge_user_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
