# Generated by Django 5.0.3 on 2024-03-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_friends_alter_friendship_user_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='occuring_when',
            new_name='occurring_when',
        ),
    ]
